Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/LineLength:
  IgnoredPatterns:
    - 'VCR\.use_cassette'
    - '(\A|\s)/.*?/'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Metrics/ModuleLength:
  Max: 150
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'consistent_comma'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'
